apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mytoolkit.fullname" . }}
  labels:
    {{- include "mytoolkit.labels" . | nindent 4 }}
data:
  MYTOOLKIT_HOST: "0.0.0.0"
  MYTOOLKIT_PORT: {{ .Values.service.port | quote }}
  MYTOOLKIT_LOG_LEVEL: {{ .Values.env.logLevel | quote }}
