{{- if and .Values.mcp.enabled .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mytoolkit.mcp.fullname" . }}
  labels:
    {{- include "mytoolkit.mcp.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "mytoolkit.mcp.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: mcp
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
