{{- if and .Values.mcp.enabled .Values.mcp.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mytoolkit.mcp.fullname" . }}
  labels:
    {{- include "mytoolkit.mcp.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.mcp.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
